import type { GeneratedProject, SelfHostConfig } from '@/types'

const GENERATED_HEADER = [
  '// This file is generated by packages/self-host.',
  '// Do not edit this file manually.',
  '',
].join('\n')

const PROJECT_LIMIT_PREFIXES: Record<GeneratedProject, readonly string[]> = {
  cli: ['CLIENT_', 'HYBRID_'],
  edge: ['API_', 'HYBRID_'],
  portal: ['CLIENT_', 'HYBRID_'],
}

export const generatedSelfHostFile = (
  project: GeneratedProject,
  config: SelfHostConfig,
): string => {
  const selfHost = {
    configs: projectConfigs(project, config),
    limits: projectLimits(project, config),
  }

  return `${GENERATED_HEADER}export const selfHost = ${JSON.stringify(selfHost, null, 2)} as const\n\nexport default selfHost\n`
}

const projectConfigs = (
  project: GeneratedProject,
  config: SelfHostConfig,
): Record<string, unknown> => {
  if (project === 'edge') return config.edge
  if (project === 'portal') {
    return {
      ...config.portal,
      apiOrigin: config.edge.origin,
    }
  }

  return {}
}

const projectLimits = (
  project: GeneratedProject,
  config: SelfHostConfig,
): Record<string, unknown> => {
  const prefixes = PROJECT_LIMIT_PREFIXES[project]
  const entries = Object.entries(config.limits).filter(([key]) =>
    prefixes.some(prefix => key.startsWith(prefix)),
  )

  return Object.fromEntries(entries)
}
