// This file is generated by packages/self-host.
// Do not edit this file manually.
export const selfHost = {
  "configs": {
    "origin": "https://secret-api.witt.im",
    "workerName": "secret-edge"
  },
  "limits": {
    "HYBRID_MAX_TEXT_BYTES": 50000,
    "HYBRID_MAX_TEXT_CIPHER_BYTES": 70000,
    "HYBRID_MAX_FILE_MB": 10,
    "HYBRID_MAX_FILE_CIPHER_MB": 15,
    "HYBRID_MAX_READS": 10,
    "HYBRID_MAX_SECRET_TTL_SECONDS": 3600,
    "API_PENDING_UPLOAD_TTL_SECONDS": 900,
    "API_TRACKING_TTL_SECONDS": 86400,
    "API_R2_UPLOAD_URL_TTL_SECONDS": 900
  }
} as const

export default selfHost
