// This file is generated by packages/self-host.
// Do not edit this file manually.
export const selfHost = {
  "configs": {},
  "limits": {
    "HYBRID_MAX_TEXT_BYTES": 50000,
    "HYBRID_MAX_TEXT_CIPHER_BYTES": 70000,
    "HYBRID_MAX_FILE_MB": 10,
    "HYBRID_MAX_FILE_CIPHER_MB": 15,
    "HYBRID_MAX_READS": 10,
    "HYBRID_MAX_SECRET_TTL_SECONDS": 3600,
    "CLIENT_VALID_EXPIRATIONS_SECONDS": [
      300,
      900,
      1800,
      3600
    ],
    "CLIENT_VALID_LINK_COUNTS": [
      1,
      3,
      5,
      10
    ]
  }
} as const

export default selfHost
